# Generated by Django 6.0.2 on 2026-02-25 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF files only', upload_to='resumes/')),
                ('candidate_name', models.CharField(help_text='Full name of the candidate', max_length=100)),
                ('candidate_email', models.EmailField(help_text='Email of the candidate', max_length=254)),
                ('candidate_phone', models.CharField(blank=True, help_text='Phone number of the candidate', max_length=20)),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from PDF')),
                ('match_score', models.IntegerField(default=0, help_text='Match score percentage')),
                ('status', models.CharField(choices=[('shortlisted', 'Shortlisted'), ('moderate', 'Moderate'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('skills_found', models.TextField(blank=True, help_text='Skills found in resume')),
                ('experience_years', models.FloatField(default=0, help_text='Total years of experience found')),
                ('education_found', models.CharField(blank=True, help_text='Education level found', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When resume was processed', null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='jobs.job')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('job', 'candidate_email')},
            },
        ),
    ]
