# Generated by Django 6.0.2 on 2026-02-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('applicant', 'Applicant'), ('admin', 'Admin')], default='applicant', max_length=20),
        ),
    ]
